---
trigger:
  - main

pool:
  name: Default

variables:
  imageName: 'philip-flask-cicd'

steps:
  - script: |
      python3 -m pip install --break-system-packages -r requirements.txt || true
      pip install --upgrade pip || true
      docker build -t $(imageName) . || true
    displayName: 'Build and Dockerize Flask App'

  - script: |
      echo "Current working directory is: $PWD"
      ls -l
    displayName: 'Show pipeline working directory'  

  - task: CopyFilesOverSSH@0
    inputs:
      sshEndpoint: 'ec2-ssh-service-connection'
      sourceFolder: '$(System.DefaultWorkingDirectory)'
      contents: '**'
      targetFolder: '/home/ubuntu/flaskcicd'
    displayName: 'Copy source code to EC2'

  - task: SSH@0
    inputs:
      sshEndpoint: 'ec2-ssh-service-connection'
      runOptions: 'inline'
      inline: |
        cd /home/ubuntu/flaskcicd
        docker stop flaskapp || true
        docker rm flaskapp || true
        docker build -t flaskapp .
        docker run -d -p 5000:5000 --name flaskapp flaskapp
    displayName: 'Deploy to EC2 instance'
